### ISSUE TITLE
Old Numpy and Scipy versions in dependencies

### ISSUE THREAD

**Issue by TobiasM95** [GoktugOcal/LiveF1#15]
Hi, I recently tried to use the library in my own project but couldn't install it due to the dependencies (which are quite old now specifically numpy and scipy). I also tried to install it with python 3.13 on windows which did not work due to scipy.

I did a scan of the code to see if there are obvious incompatibilities if I'd bump up versions of the dependencies and didn't find many.
What I did was:
let all dependencies install with the latest available version and then pin them to the result:
```
jellyfish==1.2.1
numpy==2.4.2
pandas==3.0.0
python_dateutil==2.9.0.post0
Requests==2.32.5
setuptools==82.0.0
ujson==5.11.0
websockets==16.0
scipy==1.17.0
tabulate==0.9.0
beautifulsoup4==4.14.3
lxml==6.0.2
```
then ran all the test scripts. only table_register.py failed with:
```python
16:06:56 - Silver tables are being generated.
16:06:56 - Failed to generate silver table 'SectorDiff': Cannot multiply 'timedelta64[us]' by bool, explicitly cast to integers instead
16:06:57 - Failed to generate silver table 'laps': Cannot multiply 'timedelta64[us]' by bool, explicitly cast to integers instead
16:06:57 - Failed to generate silver table 'carTelemetry': Cannot multiply 'timedelta64[us]' by bool, explicitly cast to integers instead
16:06:57 - 'raceControlMessages' has been generated and saved to the silver lake. You can access it from 'session.raceControlMessages'.
16:06:57 - Gold tables are being generated.
16:06:57 - Failed to generate gold table 'SectorLeaders': Cannot multiply 'timedelta64[us]' by bool, explicitly cast to integers instead
Traceback (most recent call last):
  File "C:\Users\tobim\Documents\Programming\SmallProjects\LiveF1\test\table_register.py", line 34, in <module>
    print(session.SectorDiff.head().to_markdown())
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'SectorDiff'
```
which I fixed with:
```python
# old
# all_laps_df["LapStartTime"] = (new_ts.isnull() * all_laps_df["LapStartTime"]) + new_ts.fillna(timedelta(0))
# new
all_laps_df["LapStartTime"] = new_ts.combine_first(all_laps_df["LapStartTime"])
```
in `silver_functions.py` -> `generate_laps_table`

and then everything worked with Python 3.13.
An alternative would be
```python
all_laps_df["LapStartTime"] = new_ts.where(new_ts.notna(), all_laps_df["LapStartTime"])
```

In case you don't want to update the dependencies, you could change this statement and I think it would run with newer dependencies and the old dependencies and multiple python versions but you might know better how this runs and how you handle dependencies.

**Comment by GoktugOcal** [comment]
resolved with PR https://github.com/GoktugOcal/LiveF1/pull/16
